excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://zlindsey.github.io
title: Zac Lindsey
tagline: Business Lawyer | Observer
description: I represent startups and business owners who love what they do and can't wait to do the next thing, however they've defined next.<br />
paginate: 5